services:
  producer-csv:
    container_name: producer-csv
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uv", "run", "main_csv.py", "-f", "merged/latency_data.csv", "-i", "0.5", "-s", "5", "-y", "network_trafic"]
    environment:
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - nwdaf-network

  producer-tshark:
    container_name: producer-tshark
    build:
      context: .
      dockerfile: Dockerfile.tshark
    environment:
      CAPTURE_INTERFACE: ${CAPTURE_INTERFACE:-dummy0}
      PORT: ${TSHARK_PORT:-8124}
      CELL_INDEX: ${CELL_INDEX:-1}
      INTERVAL: ${INTERVAL:-0}
      SEND_INTERVAL: ${SEND_INTERVAL:-5}
      EVENT_TYPE: ${EVENT_TYPE:-network_trafic}
    ports:
      - "${TSHARK_PORT:-8124}:${TSHARK_PORT:-8124}"
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN

networks:
  nwdaf-network:
    external: true
